kind: Service
apiVersion: v1
metadata:
 name: pdfgenerator
 annotations:
   prometheus.io/scrape: 'true'
 labels:
   name: pdfgenerator
spec:
 selector:
   tier: backend
   name: pdfgenerator
 type: ClusterIP
 ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
